In [3]:
def sort_asc_2_els(a: list) -> list:
    if len(a) == 2:
        if a[0] < a[1]:
            return a
        else:
            return [a[1],a[0]]
    else: 
        return None

In [4]:
print(sort_asc_2_els([4,3]))

[3, 4]


In [9]:
def check(a : list) -> bool:
    if a[0] < a[1] and a[1] < a[2]:
        return True
    else:
        return False
    
def sort_asc_3_els(a : list) -> list:
    if a[0] < a[1]:
        if a[1] < a[2]:
            a = [a[0],a[1],a[2]]
        else:
            a = [a[0],a[2],a[1]]
    else:
        a = [a[1],a[0],a[2]]
    if check(a) == True:
        return a
    else:
        return sort_asc_3_els(a)


In [10]:

# print(sort_3_els([3,9,6]))
# print(sort_3_els([6,9,3]))
print(sort_asc_3_els([9,6,3]))

[3, 6, 9]


## Bubble sort
compare two elements, times (n-1)!, mỗi vòng so sánh, sẽ giảm length-1

In [24]:
import numpy as np

np.random.seed(0)

def sort_bubble_asc(a: list, count: int = 1) -> list:
    endPoint = len(a)-1
    count = 0
    while endPoint > 0:
        count +=1
        swap = False
        for i in range(0,endPoint):
            if a[i] > a[i+1]:
                a[i],a[i+1] = a[i+1],a[i]
                swap = True
        if swap == False:
            break
        endPoint -=1
    print(f'counts: {count}')
    return a
    
a = np.random.randint(0,100,10)
print(f'input: {a}')
print(f'output: {sort_bubble_asc(a)}')
# ví dụ: 4 cặp, mảng có 5 els.4 lần / vòng lặp. 4^2. N địa diện cho số phần tử của mảng. (N-1)^2. nói N^2. N^0



input: [44 47 64 67 67  9 83 21 36 87]
[44 47 64 67 67  9 83 21 36 87]
[44 47 64 67  9 67 21 36 83 87]
[44 47 64  9 67 21 36 67 83 87]
[44 47  9 64 21 36 67 67 83 87]
[44  9 47 21 36 64 67 67 83 87]
[ 9 44 21 36 47 64 67 67 83 87]
[ 9 21 36 44 47 64 67 67 83 87]
counts: 7
output: [ 9 21 36 44 47 64 67 67 83 87]


#### func sort_bubble(array,[asc=True])

In [26]:
import numpy as np

np.random.seed(0)

def sort_bubble(a: list, asc : bool = True) -> list:
    endPoint = len(a)-1
    count = 0
    while endPoint > 0:
        count +=1
        swap = False
        for i in range(0,endPoint):
            if a[i] < a[i+1]:
                a[i],a[i+1] = a[i+1],a[i]
                swap = True
        if swap == False:
            break
        endPoint -=1
    print(f'counts: {count}')
    return a
    
a = np.random.randint(0,100,10)
print(f'input: {a}')
print(f'output: {sort_bubble(a, asc=False)}')


input: [44 47 64 67 67  9 83 21 36 87]
[47 64 67 67 44 83 21 36 87  9]
[64 67 67 47 83 44 36 87 21  9]
[67 67 64 83 47 44 87 36 21  9]
[67 67 83 64 47 87 44 36 21  9]
[67 83 67 64 87 47 44 36 21  9]
[83 67 67 87 64 47 44 36 21  9]
[83 67 87 67 64 47 44 36 21  9]
[83 87 67 67 64 47 44 36 21  9]
[87 83 67 67 64 47 44 36 21  9]
counts: 9
output: [87 83 67 67 64 47 44 36 21  9]


In [14]:
b = [3,1]
b[0],b[1] = b[1],b[0]
print(b)

[1, 3]


## SELECTION SORT
find min, move to first position

In [136]:
import numpy as np
np.random.seed(0)

def sort_selection_asc(a: list, position: int = 0) -> list:
    length = len(a)
    min = a[position]
    i_min = position
    
    for i in range(position,length):
        if a[i] < min:
            min = a[i]
            i_min = i
    a[i_min] = a[position]
    a[position] = min
    
    if position < length-2:
        return sort_selection_asc(a, position+1)
    else:
        print(f'count: {position+1}')
        return a

    
a = np.random.randint(0,100,13)
print(f'input: {a}')
print(f'output: {sort_selection_asc(a)}')
     

input: [44 47 64 67 67  9 83 21 36 87 70 88 88]
count: 12
output: [ 9 21 36 44 47 64 67 67 70 83 87 88 88]


## INSERTION SORT
select current ele, compare with els that is before, then insert

In [137]:
import numpy as np
np.random.seed(0)

def sort_insert_asc(a: list, position: int = 0) -> list:
    check = a[position]
    for i in range(position-1,-1,-1):
        if check < a[i]:
            a[i+1] = a[i]
            a[i] = check
    if position < len(a)-1:
        return sort_insert_asc(a, position+1)
    else:
        print(f'count: {position}')
        return a
a = np.random.randint(0,100,20)
# a = [1,3,7,2,3]
print(f'input: {a}')
print(f'output: {sort_insert_asc(a)}')

input: [44 47 64 67 67  9 83 21 36 87 70 88 88 12 58 65 39 87 46 88]
count: 19
output: [ 9 12 21 36 39 44 46 47 58 64 65 67 67 70 83 87 87 88 88 88]


## MERGE SORT


[mô phỏng code](https://docs.google.com/presentation/d/1uNi4BuD9KNc2awQR-fgeOg1Uc8Z-pm244eO_7TKh_DA/edit?usp=sharing)

In [12]:
def sort_merge_asc(a : list) -> None:
    if len(a) <= 1:
        return a
    
    i_merge = len(a) // 2
    left_a = a[:i_merge]
    right_a = a[i_merge:]
    
    left_a = sort_merge_asc(left_a)
    right_a = sort_merge_asc(right_a)

    return merge_els(left_a, right_a)


def merge_els(left : list, right: list):
    result = []
    i = 0
    j = 0
    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i+=1
        else:
            result.append(right[j])
            j +=1
    while i < len(left):
        result.append(left[i])
        i+=1
    while j < len(right):
        result.append(right[j])
        j+=1
    return result

a = [44, 47, 64,3,5,1,5,3]
print(f'input: {a}')
print(f'output: {sort_merge_asc(a)}')

input: [44, 47, 64, 3, 5, 1, 5, 3]
output: [1, 3, 3, 5, 5, 44, 47, 64]


In [8]:
def merge_2_array(a, b):
    result = []
    i = 0
    j = 0
    while i < len(a) and j < len(b):
        if a[i] <= b[j]:
            result.append(a[i])
            i+=1
        else:
            result.append(b[j])
            j +=1
    while i < len(a):
        result.append(a[i])
        i+=1
    while j < len(b):
        result.append(b[j])
        j+=1
    return result
a = [3,5,9]
b = [4,6,7,10,15]
print(merge_2_array(a,b))

[3, 4, 5, 6, 7, 9, 10, 15]


## QUICK SORT

In [41]:
def sort_quick(A: list):
    if len(A) <= 1:
        return A
    
    pivot = A[len(A)-1]
    left = []
    right = []
    middle = []
    
    for item in A:
        if item < pivot:
            left.append(item)
        elif item == pivot:
            middle.append(item)
        else:
            right.append(item)
    print(f'{left} - {middle} - {right}')
    A = sort_quick(left) + middle + sort_quick(right)
    return A

arr = [44, 4,  0,  3,  3, 39,  9 ,19,21,47]
print(f'input: {arr}')
print(f'count: ')
print(f'output: {sort_quick(arr)}')

input: [44, 4, 0, 3, 3, 39, 9, 19, 21, 47]
count: 
[44, 4, 0, 3, 3, 39, 9, 19, 21] - [47] - []
[4, 0, 3, 3, 9, 19] - [21] - [44, 39]
[4, 0, 3, 3, 9] - [19] - []
[4, 0, 3, 3] - [9] - []
[0] - [3, 3] - [4]
[] - [39] - [44]
output: [0, 3, 3, 4, 9, 19, 21, 39, 44, 47]


## Heap sort

- giống binary search tree. nhưng thực chất là 1 array
- số nút có lá: i = (n-2)//2 với n = len(arr). nếu n lẻ => nút cuối có 2 lá
- nút con / lá: 2i+ 1, 2i+2

[Hướng dẫn](https://www.youtube.com/watch?v=EVEssrDhfCI)

![Image](https://scontent.fsgn2-6.fna.fbcdn.net/v/t39.30808-6/355677434_5939937556112664_6906267943053742993_n.jpg?_nc_cat=110&cb=99be929b-3346023f&ccb=1-7&_nc_sid=0debeb&_nc_ohc=Riylxmv-W9oAX9q458A&_nc_ht=scontent.fsgn2-6.fna&oh=00_AfBhE9Q_q0l8qi_ut0vFqznCjrXiMivcM3XZuaO2513iPA&oe=649A6C03)

In [73]:
import numpy as np

def swap(arr : list, i : int = 0):
    n = len(arr)
    j = (n-2)//2
    mod = n % 2
    # loop from i to j (node có lá)
    while i  <= j:
        # check node có 1 lá hay 2 lá. (mod == 0 => 1 lá)
        # swap if node < lá
        if i == j and mod == 0:
            if arr[i] > arr[2*i+1]:
                arr[2*i+1], arr[i] = arr[i], arr[2*i+1]
        else:
            if arr[i] > arr[2*i+1] and arr[i] > arr[2*i+2]:
                if arr[2*i+1] <= arr[2*i+2]:
                    arr[2*i+1], arr[i] = arr[i], arr[2*i+1]
                elif arr[2*i+1] > arr[2*i+2]:
                    arr[2*i+2], arr[i] = arr[i], arr[2*i+2]
            elif arr[i] > arr[2*i+1]:
                arr[2*i+1], arr[i] = arr[i], arr[2*i+1]
            elif arr[i] > arr[2*i+2]:
                arr[2*i+2], arr[i] = arr[i], arr[2*i+2]
        i += 1
    return arr

def sort_heap(arr : list, arr_new : list = []) -> list:
    n = len(arr)
    
    # check els 2 trở lên, sẽ swap
    if n <= 1:
        arr_new.append(arr[0])
        return arr_new

    # swap from i -> 0
    i = (n-2)//2
    while i >= 0:
        swap(arr, i)
        i -= 1
        
    # swap arr[0] <=> arr[n-1]
    arr[0], arr[n-1] = arr[n-1], arr[0]
    # print(f'swaped end: {arr}')
    
    # insert min into new array, continue sort_heap lại sau khi cắt array
    arr_new.append(arr[-1])
    return sort_heap(arr[:-1],arr_new)
    

# np.random.seed(4)
arr = np.random.randint(0,100,20)
sort_heap(arr)

[1, 9, 10, 10, 12, 27, 28, 28, 31, 41, 41, 43, 48, 54, 58, 60, 63, 65, 96, 97]